before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
    paths:
      - .gradle/wrapper/
      - .gradle/caches/

stages:
  - assemble
  - test
  - deploy

assemble:
  stage: assemble
  image: openjdk:11.0-jdk

  only:
    - web-dev
    - main
    - web
    - merge_requests
     
  script:
    - cd sbsweb
    - chmod +x gradlew
    - ./gradlew assemble
    - mkdir -p target
    - mv build/libs/sbsweb-0.0.1.jar target/sbsweb.jar

  artifacts:
    paths:
      - sbsweb/target/sbsweb.jar
      
test:
  stage: test
  image: openjdk:11.0-jdk

  only:
    - merge_requests
    - web
  
  script:
    - cd sbsweb
    - chmod +x gradlew
    - ./gradlew test

deploy:
  stage: deploy
  image: docker:19.03.1

  only:
    - web-dev
    - main
    - web
  
  script:
    - docker build -t sbsweb-image -f docker/Dockerfile.sbsweb .
    - docker stop sbsweb-container || true
    - docker rm sbsweb-container || true
    - docker run -d -p 8080:8080 --name sbsweb-container sbsweb-image
